# Generated by Django 5.1.7 on 2025-03-17 15:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=255, verbose_name='Full Name')),
                ('phone', models.CharField(max_length=20, verbose_name='Phone Number')),
                ('company_name', models.CharField(max_length=255, verbose_name='Company Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('instagram', models.CharField(blank=True, max_length=255, null=True, verbose_name='Instagram Handle')),
                ('facebook', models.CharField(blank=True, max_length=255, null=True, verbose_name='Facebook Profile')),
                ('twitter', models.CharField(blank=True, max_length=255, null=True, verbose_name='Twitter Handle')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='Bio')),
                ('customer_type', models.CharField(choices=[('general', 'General'), ('vip', 'VIP')], max_length=10, verbose_name='Customer Type')),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='profile_photos/', verbose_name='Profile Photo')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Customer Profile',
                'verbose_name_plural': 'Customer Profiles',
            },
        ),
        migrations.CreateModel(
            name='VCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qr_codes/')),
                ('portfolio_link', models.URLField()),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='vcards.customer')),
            ],
        ),
    ]
