# Generated by Django 5.1.7 on 2025-03-18 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vcards', '0002_alter_customer_customer_type_vipprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='cover_photo',
            field=models.ImageField(blank=True, null=True, upload_to='cover_photos/', verbose_name='Cover Photo'),
        ),
        migrations.AddField(
            model_name='customer',
            name='linkedin',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='LinkedIn Profile'),
        ),
        migrations.AddField(
            model_name='customer',
            name='personal_website',
            field=models.URLField(blank=True, null=True, verbose_name='Personal Website'),
        ),
        migrations.AddField(
            model_name='customer',
            name='tiktok',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='TikTok Profile'),
        ),
        migrations.AddField(
            model_name='customer',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='WhatsApp Number'),
        ),
        migrations.AddField(
            model_name='customer',
            name='youtube',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='YouTube Channel'),
        ),
    ]
