# Generated by Django 5.1.7 on 2025-03-16 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vcards', '0003_remove_userprofile_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vcard',
            name='email',
            field=models.EmailField(default='mail@gmail.com', max_length=254),
        ),
    ]
