# Generated by Django 5.1.7 on 2025-03-18 11:49

import vcards.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vcards', '0003_customer_cover_photo_customer_linkedin_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['user_name'], 'verbose_name': 'Customer Profile', 'verbose_name_plural': 'Customer Profiles'},
        ),
        migrations.AlterField(
            model_name='customer',
            name='cover_photo',
            field=models.ImageField(blank=True, null=True, upload_to=vcards.models.cover_photo_path, verbose_name='Cover Photo'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to=vcards.models.profile_photo_path, verbose_name='Profile Photo'),
        ),
        migrations.AlterField(
            model_name='vcard',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to=vcards.models.qr_code_path),
        ),
        migrations.AlterField(
            model_name='vipprofile',
            name='custom_banner_image',
            field=models.ImageField(blank=True, null=True, upload_to=vcards.models.vip_banner_path, verbose_name='Banner Image'),
        ),
    ]
