# Generated by Django 5.1.7 on 2025-07-17 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vcards', '0003_rename_about_student_about_me_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='college',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
