# Generated by Django 5.1.7 on 2025-03-18 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vcards', '0004_alter_customer_options_alter_customer_cover_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='cover_photo',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='cover_photos/', verbose_name='Cover Photo'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='profile_photo',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='profile_photos/', verbose_name='Profile Photo'),
        ),
    ]
