# Generated by Django 5.1.7 on 2025-07-18 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vcards', '0005_college_remove_student_skills_alter_skill_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='college',
            old_name='location',
            new_name='address',
        ),
        migrations.AddField(
            model_name='college',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='college',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='college',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='college_logos/'),
        ),
        migrations.AddField(
            model_name='college',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='college',
            name='slogan',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='college',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
