# Generated by Django 5.1.7 on 2025-03-19 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vcards', '0005_alter_customer_cover_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vipprofile',
            name='password',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Password'),
        ),
    ]
