# Generated by Django 5.2.4 on 2025-07-30 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vcards', '0006_rename_location_college_address_college_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='messenger',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='whatsapp',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='messenger',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='whatsapp',
            field=models.URLField(blank=True, null=True),
        ),
    ]
