# Generated by Django 5.1.7 on 2025-03-19 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vcards', '0007_vipprofile_vcard_saves_vipprofile_vcard_taps_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='nfc_taps',
            field=models.IntegerField(default=0),
        ),
    ]
