# Generated by Django 5.2.4 on 2025-07-30 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vcards', '0007_clientprofile_messenger_clientprofile_whatsapp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientprofile',
            name='whatsapp',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='whatsapp',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
