# Generated by Django 5.1.7 on 2025-03-19 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vcards', '0008_customer_nfc_taps'),
    ]

    operations = [
        migrations.AddField(
            model_name='vipprofile',
            name='accent_color',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='vipprofile',
            name='company_logo',
            field=models.ImageField(blank=True, null=True, upload_to='company_logos/'),
        ),
        migrations.AddField(
            model_name='vipprofile',
            name='custom_background',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='vipprofile',
            name='custom_font',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vipprofile',
            name='custom_stylesheet',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vipprofile',
            name='primary_color',
            field=models.CharField(default='#ffffff', max_length=7),
        ),
        migrations.AddField(
            model_name='vipprofile',
            name='secondary_color',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
