# Generated by Django 5.2.4 on 2025-08-05 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vcards', '0008_alter_clientprofile_whatsapp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='cvs/'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='cvs/'),
        ),
    ]
