# Generated by Django 5.1.7 on 2025-03-19 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vcards', '0009_vipprofile_accent_color_vipprofile_company_logo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vipprofile',
            name='company_logo',
            field=models.ImageField(max_length=255, upload_to='company_logos/'),
        ),
    ]
