# Generated by Django 5.1.7 on 2025-03-20 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vcards', '0010_alter_vipprofile_company_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='vcard_saves',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customer',
            name='vcard_views',
            field=models.IntegerField(default=0),
        ),
    ]
