# Generated by Django 5.1.7 on 2025-03-21 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vcards', '0011_customer_vcard_saves_customer_vcard_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vipprofile',
            name='company_logo',
        ),
        migrations.AddField(
            model_name='customer',
            name='company_logo',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='company_logos/'),
        ),
    ]
