# Generated by Django 5.1.7 on 2025-03-25 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vcards', '0014_customer_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='password',
        ),
    ]
