# Generated by Django 5.1.7 on 2025-03-28 15:07

import django.db.models.deletion
import vcards.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vcards', '0015_remove_customer_password'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='vcard',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to=vcards.models.qr_code_path),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=20, unique=True, verbose_name='Student ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='Full Name')),
                ('phone', models.CharField(max_length=15, unique=True, verbose_name='Phone Number')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email Address')),
                ('date_of_birth', models.DateField(verbose_name='Date of Birth')),
                ('address', models.TextField(verbose_name='Address')),
                ('guardian_name', models.CharField(max_length=255, verbose_name='Guardian Name')),
                ('guardian_phone', models.CharField(max_length=15, verbose_name='Guardian Phone Number')),
                ('school_name', models.CharField(max_length=255, verbose_name='School Name')),
                ('department', models.CharField(max_length=255, verbose_name='Department')),
                ('course', models.CharField(max_length=255, verbose_name='Course')),
                ('year_of_study', models.PositiveIntegerField(verbose_name='Year of Study')),
                ('linkedin', models.URLField(blank=True, null=True, verbose_name='LinkedIn Profile')),
                ('portfolio_link', models.URLField(blank=True, null=True, verbose_name='Portfolio Link')),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to=vcards.models.profile_photo_path, verbose_name='Profile Photo')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to=vcards.models.qr_code_path, verbose_name='QR Code')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User Account')),
            ],
        ),
    ]
